### ISSUE TITLE
7tv emotes not showing up

### ISSUE THREAD

**Issue by Falsernet** [sammwyy/show-emote#3]
7tv emotes aren't showing up, it shows the little icon for broken image URL instead. I tried the generated URL in a browser and did inspect element - the image URL is missing a file extension. I tried the URL in its own tab, and it didn't work, but adding '.webp' leads to the actual emote.

TL;DR: you should append '.webp'.

**Comment by sammwyy** [comment]
Fixed :)

I release a new open api ([streamoverlay/open](https://github.com/streamoverlay/open)) for emote fetching.
